### ISSUE TITLE
Error in retrieve function when using named fields

### ISSUE THREAD

**Issue by zmhassan** [AICoE/log-anomaly-detector#135]
**Describe the bug**

**Code in Question**
`anomaly_detector.py#73-76`

```python
        data, raw = self.storage.retrieve(time_range=time_span,
                                          number_of_entries=max_entries,
                                          false_data=false_positives)

```

**Error**
```
http://0.0.0.0:5001 "GET /api/false_positive HTTP/1.1" 200 36
Added noise 1 messages 
Training failed: retrieve() got an unexpected keyword argument 'number_of_entries'
Traceback (most recent call last):
  File "/Users/zhassan/git/log-anomaly-detector/app.py", line 51, in <module>
    cli(auto_envvar_prefix="LAD")
  File "/Users/zhassan/virtual_env/venv/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/zhassan/virtual_env/venv/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/zhassan/virtual_env/venv/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/zhassan/virtual_env/venv/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/zhassan/virtual_env/venv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/zhassan/git/log-anomaly-detector/app.py", line 47, in run
    anomaly_detector.run(single_run=True)
  File "/Users/zhassan/git/log-anomaly-detector/anomaly_detector/anomaly_detector.py", line 251, in run
    self.train(false_positives=false_positives)
  File "<decorator-gen-1>", line 2, in train
  File "/Users/zhassan/virtual_env/venv/lib/python3.6/site-packages/prometheus_client/context_managers.py", line 66, in wrapped
    return func(*args, **kwargs)
  File "/Users/zhassan/git/log-anomaly-detector/anomaly_detector/anomaly_detector.py", line 87, in train
    data, _ = self._load_data(self.config.TRAIN_TIME_SPAN, self.config.TRAIN_MAX_ENTRIES, false_positives)
  File "/Users/zhassan/git/log-anomaly-detector/anomaly_detector/anomaly_detector.py", line 75, in _load_data
    false_data=false_positives)
TypeError: retrieve() got an unexpected keyword argument 'number_of_entries'

```

**Expected behavior**
This should work but the interfaces where not designed properly.

**Screenshots**

**Additional context**

**Comment by zmhassan** [comment]
#134
