### ISSUE TITLE
[PR_SUBMITTED] TypeError: argument of type 'NoneType' is not iterable in fact_store feedback loop

### ISSUE THREAD

**Issue by zmhassan** [AICoE/log-anomaly-detector#136]
**Describe the bug**
When passing no false positive data the system crashes do to NoneType error

**Code in question**
anomaly_detector.py#191
```
                if dist[i] > threshold and {"message": s["message"]} not in false_positives:
```
**Error**
``` 
Inference failed: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/Users/zhassan/git/log-anomaly-detector/app.py", line 51, in <module>
    cli(auto_envvar_prefix="LAD")
  File "/Users/zhassan/virtual_env/venv/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/zhassan/virtual_env/venv/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/zhassan/virtual_env/venv/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/zhassan/virtual_env/venv/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/zhassan/virtual_env/venv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/zhassan/git/log-anomaly-detector/app.py", line 47, in run
    anomaly_detector.run(single_run=True)
  File "/Users/zhassan/git/log-anomaly-detector/anomaly_detector/anomaly_detector.py", line 261, in run
    raise ex
  File "/Users/zhassan/git/log-anomaly-detector/anomaly_detector/anomaly_detector.py", line 258, in run
    self.infer()
  File "/Users/zhassan/git/log-anomaly-detector/anomaly_detector/anomaly_detector.py", line 191, in infer
    if dist[i] > threshold and {"message": s["message"]} not in false_positives:
TypeError: argument of type 'NoneType' is not iterable
```

**Expected behavior**
When we have no false positives or when fact_store server is down it should check if false_positive is None or empty array.
 
**Additional context**
N/A

**Comment by zmhassan** [comment]
This PR should handle the NoneType error.
