### ISSUE TITLE
Unexpected crash during run.

### ISSUE THREAD

**Issue by zmhassan** [AICoE/log-anomaly-detector#139]
**Describe the bug**

```
Progress of anomaly events record 1 of 144
--
  | Inference failed: Expecting value: line 1 column 1 (char 0)
  | Traceback (most recent call last):
  | File "app.py", line 51, in <module>
  | cli(auto_envvar_prefix="LAD")
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 764, in __call__
  | return self.main(*args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 717, in main
  | rv = self.invoke(ctx)
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
  | return _process_result(sub_ctx.command.invoke(sub_ctx))
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 956, in invoke
  | return ctx.invoke(self.callback, **ctx.params)
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 555, in invoke
  | return callback(*args, **kwargs)
  | File "app.py", line 47, in run
  | anomaly_detector.run(single_run=True)
  | File "/opt/app-root/src/anomaly_detector/anomaly_detector.py", line 268, in run
  | raise ex
  | File "/opt/app-root/src/anomaly_detector/anomaly_detector.py", line 265, in run
  | self.infer(false_positives=false_positives)
  | File "/opt/app-root/src/anomaly_detector/anomaly_detector.py", line 210, in infer
  | s["predict_id"], s["message"], dist[i], s["anomaly"], self.config.FACT_STORE_URL
  | File "/opt/app-root/src/anomaly_detector/events/anomaly_event.py", line 57, in record_prediction
  | data = r.json()
  | File "/opt/app-root/lib/python3.6/site-packages/requests/models.py", line 897, in json
  | return complexjson.loads(self.text, **kwargs)
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/json/__init__.py", line 354, in loads
  | return _default_decoder.decode(s)
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/json/decoder.py", line 339, in decode
  | obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
  | raise JSONDecodeError("Expecting value", s, err.value) from None
  | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Additional context**

**Comment by zmhassan** [comment]
This was fixed long time ago.
