### ISSUE TITLE
Pip install from pypy yields dependency issues

### ISSUE THREAD

**Issue by HumairAK** [AICoE/log-anomaly-detector#274]
**Describe the bug**
Installing LAD from pypy is broken. I've tried it a few times with a different virtualenv each time and leads to the same dependency issue: 

```
$ log-anomaly-detector --help
/home/hukhan/projects/testing-playground/LAD2/venv/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
Traceback (most recent call last):
  File "/home/hukhan/projects/testing-playground/LAD2/venv/bin/log-anomaly-detector", line 6, in <module>
    from app import cli
  File "/home/hukhan/projects/testing-playground/LAD2/venv/lib/python3.7/site-packages/app.py", line 5, in <module>
    from anomaly_detector.anomaly_detector_facade import AnomalyDetectorFacade
  File "/home/hukhan/projects/testing-playground/LAD2/venv/lib/python3.7/site-packages/anomaly_detector/anomaly_detector_facade.py", line 2, in <module>
    from anomaly_detector.adapters.feedback_strategy import FeedbackStrategy
  File "/home/hukhan/projects/testing-playground/LAD2/venv/lib/python3.7/site-packages/anomaly_detector/adapters/__init__.py", line 5, in <module>
    from anomaly_detector.adapters.som_model_adapter import SomModelAdapter
  File "/home/hukhan/projects/testing-playground/LAD2/venv/lib/python3.7/site-packages/anomaly_detector/adapters/som_model_adapter.py", line 15, in <module>
    from anomaly_detector.model import SOMPYModel, W2VModel
  File "/home/hukhan/projects/testing-playground/LAD2/venv/lib/python3.7/site-packages/anomaly_detector/model/__init__.py", line 4, in <module>
    from anomaly_detector.model.sompy_model import SOMPYModel
  File "/home/hukhan/projects/testing-playground/LAD2/venv/lib/python3.7/site-packages/anomaly_detector/model/sompy_model.py", line 6, in <module>
    import sompy
  File "/home/hukhan/projects/testing-playground/LAD2/venv/lib/python3.7/site-packages/sompy/__init__.py", line 2, in <module>
    from sompy import SOM
ImportError: cannot import name 'SOM' from 'sompy' (/home/hukhan/projects/testing-playground/LAD2/venv/lib/python3.7/site-packages/sompy/__init__.py)
```

**To Reproduce**
```
$ python3 -m virtualenv venv
$ source venv/bin/activate
$ pip3 install log-anomaly-detector
$ log-anomaly-detector --help
```

**Expected behavior**
Display --help output without errors/dependency issues.

**Comment by lialosiu** [comment]
```bash
pip install git+https://github.com/compmonks/SOMPY.git
```

will fix this.

and another error: `ModuleNotFoundError: No module named 'ipdb'`

can fix by:

```bash
pip install ipdb
```

**Comment by zmhassan** [comment]
This issue is now fixed. With the latests setup.py
