### ISSUE TITLE
Pypy install leads to SOM  import error

### ISSUE THREAD

**Issue by HumairAK** [AICoE/log-anomaly-detector#292]
**Describe the bug**
Pypy installation has dependency errors

**To Reproduce**
```
# Make sure the validation and config file directories from the repo are present in working dir
python3 -m virtualenv venv
source venv/bin/activate
pip3 install log-anomaly-detector
log-anomaly-detector run --config-yaml config_files/.env_cmn_log_fmt_config.yaml --single-run True
```
**Expected behavior**
Perform a single run w/o issues. 

** The error shown: **

```└───▶ log-anomaly-detector run --config-yaml config_files/.env_cmn_log_fmt_config.yaml --single-run True
/home/hukhan/projects/testing-playground/LAD4/venv/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
Traceback (most recent call last):
  File "/home/hukhan/projects/testing-playground/LAD4/venv/bin/log-anomaly-detector", line 6, in <module>
    from app import cli
  File "/home/hukhan/projects/testing-playground/LAD4/venv/lib/python3.7/site-packages/app.py", line 5, in <module>
    from anomaly_detector.anomaly_detector_facade import AnomalyDetectorFacade
  File "/home/hukhan/projects/testing-playground/LAD4/venv/lib/python3.7/site-packages/anomaly_detector/anomaly_detector_facade.py", line 2, in <module>
    from anomaly_detector.adapters.feedback_strategy import FeedbackStrategy
  File "/home/hukhan/projects/testing-playground/LAD4/venv/lib/python3.7/site-packages/anomaly_detector/adapters/__init__.py", line 5, in <module>
    from anomaly_detector.adapters.som_model_adapter import SomModelAdapter
  File "/home/hukhan/projects/testing-playground/LAD4/venv/lib/python3.7/site-packages/anomaly_detector/adapters/som_model_adapter.py", line 15, in <module>
    from anomaly_detector.model import SOMPYModel, W2VModel
  File "/home/hukhan/projects/testing-playground/LAD4/venv/lib/python3.7/site-packages/anomaly_detector/model/__init__.py", line 4, in <module>
    from anomaly_detector.model.sompy_model import SOMPYModel
  File "/home/hukhan/projects/testing-playground/LAD4/venv/lib/python3.7/site-packages/anomaly_detector/model/sompy_model.py", line 6, in <module>
    import sompy
  File "/home/hukhan/projects/testing-playground/LAD4/venv/lib/python3.7/site-packages/sompy/__init__.py", line 2, in <module>
    from sompy import SOM
ImportError: cannot import name 'SOM' from 'sompy' (/home/hukhan/projects/testing-playground/LAD4/venv/lib/python3.7/site-packages/sompy/__init__.py)
```

The config is from the repo, this is the contents: 

```
STORAGE_DATASOURCE: "local.source"
STORAGE_DATASINK: "local.sink"
LS_INPUT_PATH: "validation_data/orders-500.log"
LS_OUTPUT_PATH: "validation_data/aug-3_25-results.txt"
INFER_ANOMALY_THRESHOLD: 1.3
INFER_TIME_SPAN: 1
INFER_LOOPS: 1
PARALLELISM: 6

```

**Comment by zmhassan** [comment]
This is fixed.

**Comment by tcxdgit** [comment]
> This is fixed.

However, when I install the latest vesion of log-anomaly-detector(0.0.1b6). I still got this error.
![image](https://user-images.githubusercontent.com/23009178/70031622-9da94900-15e6-11ea-8d80-4e0c9bfa7aac.png)

**Comment by goern** [comment]
@fridex any idea?

**Comment by zmhassan** [comment]
``` 

dependency_links=[
	"git+https://github.com/sevamoo/SOMPY.git@76b60ebd6ffd550b0f7faaf632451dfd68827bf7#egg=sompy",
    ],
```

It is because we are using a git commit as a dependency.

**Comment by zmhassan** [comment]
@fridex You can work on this if you would like just wanted to point you in the right direction.

**Comment by zmhassan** [comment]
@tcxdgit I've cut a release. 

Try this:

```
pipenv --rm
pipenv --python 3.7 
pip install log-anomaly-detector==0.0.1b1
```

This works I'm sure of it if you are still running into issues please let us know here.

**Comment by tcxdgit** [comment]
> @tcxdgit I've cut a release.
> 
> Try this:
> 
> ```
> pipenv --rm
> pipenv --python 3.7 
> pip install log-anomaly-detector==0.0.1b1
> ```
> 
> This works I'm sure of it if you are still running into issues please let us know here.

Thank you for your help!

**Comment by zak-hassan** [comment]
Awesome.
